name: "Release"
on:
 push:
  tags:
    - '*'

jobs:
  build:
    name: "Build and Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build
      - uses: softprops/action-gh-release@v1
        with:
          files: result/cv.pdf
